name: BigCoin
version: ${project.version}
main: org.xjcraft.bigcoin.BigCoin
api-version: '1.13'
depend: [SimpleSpigot, MultiCurrency]
softdepend:
  - XJLogin
authors: [reezhu]

commands:

  BigCoin:
    description: BigCoin command
    usage: /<command>
    aliases: [ bc ]
    permission: bigcoin.admin
    permission-message: You do not have permission to use this command.